# Generated by Django 3.2.13 on 2022-06-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DishTV_app', '0014_auto_20220608_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='seller',
            new_name='seller1',
        ),
    ]
